### ISSUE TITLE
Could you please inform me?

### ISSUE THREAD

**Issue by lucas3820** [Kowson/Details-Damage-Meter-for-3.3.5a#12]
Was this addon created in VScode?
Where do I find the assets (UI) to create the addon interface for wow (that works in version 3.3.5)?
Which framework used?

**Comment by Kowson** [comment]
I've used only Notepad++. I don't know about any other Addons for that.

**Comment by lucas3820** [comment]
> I've used only Notepad++. I don't know about any other Addons for that.

But, where did you get as images?

**Comment by Kowson** [comment]
Get what as images? Could you eloborate?

**Comment by lucas3820** [comment]
https://i.imgur.com/QL5iTkt.jpg
Icons
BG

**Comment by Kowson** [comment]
Depends, some of them were already in the client, and you can extract it using some app.
Newer ones I took from here: https://github.com/Gethe/wow-ui-textures
And some of them just from wow wiki etc.
