### ISSUE TITLE
Suggestion: Details TinyThreat

### ISSUE THREAD

**Issue by bkader** [Kowson/Details-Damage-Meter-for-3.3.5a#2]
I love the addon and I really find it useful! I tried my best to backport TinyThreat or even creating a threat meter plugin for it but I gave up quickly.
Is there any chance you can backport the original TinyThreat as well? Because you know your code so you're the one who knows what must be done.
Thanks in advance.

**Comment by Kowson** [comment]
I remember trying to do so, but could not find any video showing how this works and couldn't afford paying for retail so I stopped working on it. If I play WoW again I'll try to backport it too.

**Comment by bkader** [comment]
Thank you! I didn't find any video either. I spent few hours on it then I quit .. Thanks for the so-far available plugins anyways, great work.
