### ISSUE TITLE
[BUG] Grouped windows can only be resized a few pixel at a time

### ISSUE THREAD

**Issue by ghost** [Kowson/Details-Damage-Meter-for-3.3.5a#34]

**Comment by Kowson** [comment]
That one is kinda tricky, because moving a window stops resizing. And when changing size of grouped windows they are moving a bit, so need to think of workaround for this.

**Comment by Kowson** [comment]
Could you tell me how does it work on retail?
What I mean - does it:
1. resize all windows in group at once
2. resize only one window and after releasing mouse button updates all windows in the group?
I can probably implement 2.

**Comment by ghost** [comment]
It's the first way judging by this video https://www.youtube.com/watch?v=wV8m62z4dx0&t=49 but I'll be fine with the second.

**Comment by Kowson** [comment]
Okay, I've found a way to temporary fix it. It is less intuitive, but effect is the same.
Basically you can resize them in anyway you want, but they are not always attached to each other during resizing. There seems to be problem with function responsible for that.

Will deploy a release later today or tomorrow after testing whether it works.
