### ISSUE TITLE
Question: Encounter IDs and spell_mechanics  

### ISSUE THREAD

**Issue by andrew6180** [Kowson/Details-Damage-Meter-for-3.3.5a#4]
Hey, I'm interested in working on Naxx / OS / EoE since I'm currently playing the new warmane server. I've already done a bit of work on it, but I'm curious where you found the encounter IDs you're using for ToC / ulduar. 

using https://wow.tools/dbc/?dbc=dungeonencounter&build=3.3.5.12340  the encounter IDs are significantly different from the ones you're using, so I'm wondering if those aren't working or if I'm just going about it wrong?

Also, spell_mechanics is somewhat difficult to figure out. Do you have some sort of idea what each hex value represents, are they randomly given?

**Comment by Krealle** [comment]
Have you figured out how to stop it from hanging after some boss encounters by any chance?

**Comment by andrew6180** [comment]
Honestly I have no idea. 

My guess would be something to do with https://github.com/Kowson/Details-Damage-Meter-for-3.3.5a/blob/master/Details/core/control.lua#L483

which forces https://github.com/Kowson/Details-Damage-Meter-for-3.3.5a/blob/master/Details/core/meta.lua#L635

Possibly try changing  https://github.com/Kowson/Details-Damage-Meter-for-3.3.5a/blob/master/Details/core/meta.lua#L614 to `_details:InitializeCollectGarbage(false, 60)` which will schedule gc it seems? 

All of this is assuming it happens only in raid boss encounters. If its happening in solo content then it's probably something else.


You could also try increasing the addon's memory limit which seems to be in the settings somewhere.

**Comment by Krealle** [comment]
Hmm might have to try around with that. Doesn't seem to have something to do with memory, since it works just fine for solo content and content like naxx where all encounters are counted as trash cleanups.

**Comment by andrew6180** [comment]
if you could, try and run https://github.com/ajseward/Stragglers-3.3.5 during a boss encounter and see where its spending all its time during hangs. Not really sure if it will end up tanking performance or not but it's worth a shot.

**Comment by Kowson** [comment]
Hi @ajseward, I used unit IDs directly from source code of Sunwell server (it is the server i played and tested it on). 
https://github.com/RaphaelSunwell/Sunwell/tree/master/src/server/scripts/Northrend

And encounter IDs are custom made by me using DBM addon, because back on WoTLK there was no start encounter event, so I had to somehow create my own :P

Feel free to ask any questions and contribute to improving this addon. Cheers!

**Comment by Kowson** [comment]
And about what Krealle said - that was my main goal to fix that bug, but I had no idea what is this caused by. During Ulduar it happened always everytime around Kologarn fight, but I'm new to addons so I didn't really know how to debug that.

**Comment by andrew6180** [comment]
Alright cool, I was wondering why dbm was included. 
I specifically was wondering about the `spell_mechanics` table, like here 

```lua
spell_mechanics =	{
    [58678] = {0x1}, --> Rock Shards
    [58960] = {0x40}, --> Leap 10
    [60894] = {0x40}, -->  Leap 25
    [58663] = {0x100}, --> Stomp 10
    [60880] = {0x100}, --> Stomp 25
    [58666] = {0x1}, --> Impale 10
    [60882] = {0x1}, --> Impale 25
    },
```
and what the hex values referred to, or if it was even important to fill this out.

**Comment by Kowson** [comment]
Oh, that is not important (yet?). It's about this enum:
https://github.com/Kowson/Details-Damage-Meter-for-3.3.5a/blob/699df5c1b22168993d05640954cbc403d45d2458/Details_EncounterDetails/Details_EncounterDetails.lua#L47

The thing it is not implemented in this version of Encounter Details, so you can fill it with anything, but they may be used in the future so use your intuition :D

**Comment by Krealle** [comment]
Hi, I've been able to add Naxx encounters, seemingly all you need is `boss_names` and `boss_ids` filled out. I filled out the `encounter_ids` and `encounter_ids2` with random ID's and everything seems to be working so far.

I also seem to have fixed the bug (or atleast found a temporary workaround) where it will hang after killing a boss requiring a reload. I did this by commenting out:
https://github.com/Kowson/Details-Damage-Meter-for-3.3.5a/blob/master/Details/core/control.lua#L524
```
if (_details.table_current.instance_type == "raid") then
  --> schedule captures off

  _details:CaptureSet(false, "damage", false, 15)
  _details:CaptureSet(false, "energy", false, 15)
  _details:CaptureSet(false, "aura", false, 15)
  _details:CaptureSet(false, "energy", false, 15)
  _details:CaptureSet(false, "spellcast", false, 15)

  if (_details.debug) then
	_details:Msg("(debug) freezing parser for 15 seconds.")
  end

end 
```
I don't know if commenting out this will introduce a new bug somewhere down the line, guess I'll find out for tonights raid in Ulduar. But for now, it's working in Naxx without hanging.

**Comment by andrew6180** [comment]
that's weird but makes sense if there's a bug with AceTimers never re-enabling capture. 
It's also weird that it sets energy to false twice, possible that might cause it. Regardless I have yet to encounter the issue through all of naxx 10. 

Speaking of, you should grab my fork of the addon from here https://github.com/ajseward/Details-Damage-Meter-for-3.3.5a for the time being. I'll be submitting a pull request but nothing is really tested much outside a single run of naxx.

**Comment by Kowson** [comment]
I'll check and merge that later! Thanks for the work :D
