### ISSUE TITLE
"Please eneter a password for 'Details'"

### ISSUE THREAD

**Issue by livrim** [Kowson/Details-Damage-Meter-for-3.3.5a#49]
Hello
I am facing this window on each login with newest version of Details installed. It does not pop up when i disable the addon completely. The window will disappear when i click Cancel or wait few seconds. I had similar problem with addon called Carbonite Maps but there was an option to disable global and zone channels for this addon which i can't find in Details.
![1](https://user-images.githubusercontent.com/46114158/207610031-f006d8eb-e833-462d-8dc0-1de6512e732b.png)
![2](https://user-images.githubusercontent.com/46114158/207610045-04355db1-bd70-4812-bf9f-cd9add5ff1ec.png)

**Comment by crisisdw** [comment]
I can vouch for this, it's just about the most aggrivating thing ever. I am going to attempt to remove it myself without breaking the addon but man I hope there's soon a fix for it.

**Comment by crisisdw** [comment]
Network.lua - comment out line 483 and 484 by adding -- before each line.  This has seemed to kill the password issue and it hasn't asked me for about 30 minutes (relogged and entered a bunch of instances to make sure.).

**Comment by livrim** [comment]
Couldn't see any new version added but the problem persists. 
![WoWScrnShot_031923_131822](https://user-images.githubusercontent.com/46114158/226174837-4d9b4fad-2e42-4406-8c40-e4fc92bbc91d.jpg)

**Comment by livrim** [comment]
Fixed.
Thank you!
